# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1902850-ti29.tilab.tuwien.ac.at/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s100fgga676-1Q
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /homes/s12023400/191019/sources/rtl/vicuna2_core/cvfpu/src/common_cells/include/common_cells
    /homes/s12023400/191019/sources/rtl/vicuna2_core/sva
  } -define {XIF_ON RISCV_ZVE32X OLD_VICUNA SYNTH} {
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/include/cv32e40x_pkg.sv
      /homes/s12023400/191019/sources/synthesis/cv32e40x_sim_clock_gate.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_pc_target.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_register_file_wrapper.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_cs_registers.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_clic_int_controller.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_write_buffer.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_mpu.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_prefetcher.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_instr_obi_interface.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_controller.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_wb_stage.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_data_obi_interface.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_load_store_unit.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_sequencer.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_mult.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_sleep_unit.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_a_decoder.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_prefetch_unit.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_i_decoder.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_alu.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_pma.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_decoder.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_div.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/if_c_obi.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_register_file.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_alignment_buffer.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/if_xif.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_csr.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_lsu_response_filter.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_controller_bypass.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_m_decoder.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_ex_stage.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_controller_fsm.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_if_stage.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_int_controller.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_popcnt.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_ff_one.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_b_decoder.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_alu_b_cpop.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_core.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_id_stage.sv
      /homes/s12023400/191019/sources/rtl/cv32e40x/rtl/cv32e40x_compressed_decoder.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/cvfpu/src/fpnew_pkg.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_pkg.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/vproc_config.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_mul_block.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_pending_wr.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_vregunpack.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_div.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_queue.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_decoder.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_sld.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_fpu.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_elem.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_result.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_lsu.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/cv32e40x_div.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_xif.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_pipeline.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_vregpack.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_unit_mux.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_vreg_wr_mux.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_vregfile.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_unit_wrapper.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_core.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_pipeline_wrapper.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_dispatcher.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_mul.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_alu.sv
      /homes/s12023400/191019/sources/rtl/vicuna2_core/rtl/vproc_div_shift_clz.sv
      /homes/s12023400/191019/sources/rtl/vproc_top.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top vproc_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter dspResource 0
# MODE: 
    rt::set_parameter webTalkPath {/homes/s12023400/191019/sources/synthesis/vicuna.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1902850-ti29.tilab.tuwien.ac.at/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
